### ISSUE TITLE
update flatpickr themes

### ISSUE THREAD

**Issue by JoelGraham93** [Matsuuu/lit-flatpickr#3]
https://github.com/Matsuuu/lit-flatpickr/blob/5dab9faf676ddb2e1ec7303c8affc474a64e1f2b/src/StyleLoader.ts#L3

flatpickr.js no longer adds the `.showTimeInput` class to `.flatpickr-calendar`

Version 4.6.3 themes require `.showTimeInput` to set `.flatpickr-time` height to 40px
```css
.flatpickr-calendar.showTimeInput.hasTime .flatpickr-time {
  height: 40px;
  border-top: 1px solid #eceef1;
}
```
Currently the time picker is not displaying in `lit-flatpickr` version `0.2.4`
